### ISSUE TITLE
Ch-Ch-Changes (Dashboard overhaul)

### ISSUE THREAD

**Issue by michaelpelletier** [MegaGameSociety/WatchTheSkiesDashboard#29]
I miss you, David Bowie. :(

Okay, changes from meeting today with Noam. The Dashboard itself needs to be redesigned / hugely resized to work better for a Projector. This will mean the following changes:
- [x] Much larger font.
- [x] Different colours. Basically more contrast and brighter, since the projectors are likely to wash it all out a bit.
- [x] Probably remove country/income side area and make a Ticker across the bottom. That space can be used more for the News Article Images. Ticker should have both a value as well as up/down arrows for changes.
- [x] Probably limit to one News Article at a time, do some animate stuff to flip between 2-3 of them. 
- [x] Terror tracker should be more of a thermometer (I have a rough sketch of this) instead of a wheel. Colour will change based on severity. Already have things in mind for how this should look and work.
- [x] Rioters / Military will be removed for now, unfortunately. Possibly will be reinstated once we have better uses for them.

**Comment by FifthSurprise** [comment]
@michaelpelletier This might be an unnecessary suggestion but gradient seems perfect for terror tracker as we can mess around with the ratio of Terror/Total Terror with impunity and always have a valid color.

Also, the api can deliver something like 15 news articles per round (3 players, 5 articles each, per round).  This is actually a minimum estimate since it might be a combination of the current and previous round, but I might adjust it so that older items get popped off.  I'm not sure how many is the "correct" # to have available on the dash but keep in mind players will sit there and watch through a "news cycle" to see what's going on.  Might be a good idea to have a more prominent timestamp (data of which I can provide).

**Comment by FifthSurprise** [comment]
@michaelpelletier Edited the title just so that I don't get confused every time I see David Bowie reference.
